// Minecraft clone made with THREE.js
// Static data for defining items
// By Amy Burnett
// =======================================================================
// Importing

import { BlockId } from "./blockId.js";
import { ItemId } from "./itemId.js";
import { createBlockModel } from "./itemModel.js";
import { loadModel } from "./modelLoading.js";
import { ToolType } from "./tool.js";

// =======================================================================

// Note: order must match enum order
export const itemStaticData = [
    {
        id: ItemId.AirBlock,
        name: "AirBlock",
        maxStackSize: 64,
        texture: null,
        textures: null,
        blockToPlace: BlockId.Air,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.GrassBlock,
        name: "GrassBlock",
        maxStackSize: 64,
        texture: "assets/texture_grass_side.png",
        textureFilenames: {
            top:    "assets/texture_grass_top.png",
            front:  "assets/texture_grass_side.png",
            back:   "assets/texture_grass_side.png",
            left:   "assets/texture_grass_side.png",
            right:  "assets/texture_grass_side.png",
            bottom: "assets/texture_dirt.png",
        },
        getModel: () => {return createBlockModel (ItemId.GrassBlock)},
        blockToPlace: BlockId.Grass,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.DirtBlock,
        name: "DirtBlock",
        maxStackSize: 64,
        texture: "assets/texture_dirt.png",
        textureFilenames: {
            top:    "assets/texture_dirt.png",
            front:  "assets/texture_dirt.png",
            back:   "assets/texture_dirt.png",
            left:   "assets/texture_dirt.png",
            right:  "assets/texture_dirt.png",
            bottom: "assets/texture_dirt.png",
        },
        getModel: () => {return createBlockModel (ItemId.DirtBlock)},
        blockToPlace: BlockId.Dirt,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.StoneBlock,
        name: "StoneBlock",
        maxStackSize: 64,
        texture: "assets/texture_stone.png",
        textureFilenames: {
            top:    "assets/texture_stone.png",
            front:  "assets/texture_stone.png",
            back:   "assets/texture_stone.png",
            left:   "assets/texture_stone.png",
            right:  "assets/texture_stone.png",
            bottom: "assets/texture_stone.png",
        },
        getModel: () => {return createBlockModel (ItemId.StoneBlock)},
        blockToPlace: BlockId.Stone,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.SandBlock,
        name: "SandBlock",
        maxStackSize: 64,
        texture: "assets/texture_sand.png",
        textureFilenames: {
            top:    "assets/texture_sand.png",
            front:  "assets/texture_sand.png",
            back:   "assets/texture_sand.png",
            left:   "assets/texture_sand.png",
            right:  "assets/texture_sand.png",
            bottom: "assets/texture_sand.png",
        },
        getModel: () => {return createBlockModel (ItemId.SandBlock)},
        blockToPlace: BlockId.Sand,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.WaterBlock,
        name: "WaterBlock",
        maxStackSize: 64,
        texture: "assets/texture_water.png",
        textureFilenames: {
            top:    "assets/texture_water.png",
            front:  "assets/texture_water.png",
            back:   "assets/texture_water.png",
            left:   "assets/texture_water.png",
            right:  "assets/texture_water.png",
            bottom: "assets/texture_water.png",
        },
        getModel: () => {return createBlockModel (ItemId.WaterBlock)},
        blockToPlace: BlockId.Water,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.LogBlock,
        name: "LogBlock",
        maxStackSize: 64,
        texture: "assets/texture_log_top.png",
        textureFilenames: {
            top:    "assets/texture_log_top.png",
            front:  "assets/texture_log_side.png",
            back:   "assets/texture_log_side.png",
            left:   "assets/texture_log_side.png",
            right:  "assets/texture_log_side.png",
            bottom: "assets/texture_log_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.LogBlock)},
        blockToPlace: BlockId.Log,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.LeavesBlock,
        name: "LeavesBlock",
        maxStackSize: 64,
        texture: "assets/texture_leaves.png",
        textureFilenames: {
            top:    "assets/texture_leaves.png",
            front:  "assets/texture_leaves.png",
            back:   "assets/texture_leaves.png",
            left:   "assets/texture_leaves.png",
            right:  "assets/texture_leaves.png",
            bottom: "assets/texture_leaves.png",
        },
        getModel: () => {return createBlockModel (ItemId.LeavesBlock)},
        blockToPlace: BlockId.Leaves,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.CoalOreBlock,
        name: "CoalOreBlock",
        maxStackSize: 64,
        texture: "assets/texture_coal_ore.png",
        textureFilenames: {
            top:    "assets/texture_coal_ore.png",
            front:  "assets/texture_coal_ore.png",
            back:   "assets/texture_coal_ore.png",
            left:   "assets/texture_coal_ore.png",
            right:  "assets/texture_coal_ore.png",
            bottom: "assets/texture_coal_ore.png",
        },
        getModel: () => {return createBlockModel (ItemId.CoalOreBlock)},
        blockToPlace: BlockId.CoalOre,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.IronOreBlock,
        name: "IronOreBlock",
        maxStackSize: 64,
        texture: "assets/texture_iron_ore.png",
        textureFilenames: {
            top:    "assets/texture_iron_ore.png",
            front:  "assets/texture_iron_ore.png",
            back:   "assets/texture_iron_ore.png",
            left:   "assets/texture_iron_ore.png",
            right:  "assets/texture_iron_ore.png",
            bottom: "assets/texture_iron_ore.png",
        },
        getModel: () => {return createBlockModel (ItemId.IronOreBlock)},
        blockToPlace: BlockId.IronOre,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.GoldOreBlock,
        name: "GoldOreBlock",
        maxStackSize: 64,
        texture: "assets/texture_gold_ore.png",
        textureFilenames: {
            top:    "assets/texture_gold_ore.png",
            front:  "assets/texture_gold_ore.png",
            back:   "assets/texture_gold_ore.png",
            left:   "assets/texture_gold_ore.png",
            right:  "assets/texture_gold_ore.png",
            bottom: "assets/texture_gold_ore.png",
        },
        getModel: () => {return createBlockModel (ItemId.GoldOreBlock)},
        blockToPlace: BlockId.GoldOre,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.DiamondOreBlock,
        name: "DiamondOreBlock",
        maxStackSize: 64,
        texture: "assets/texture_diamond_ore.png",
        textureFilenames: {
            top:    "assets/texture_diamond_ore.png",
            front:  "assets/texture_diamond_ore.png",
            back:   "assets/texture_diamond_ore.png",
            left:   "assets/texture_diamond_ore.png",
            right:  "assets/texture_diamond_ore.png",
            bottom: "assets/texture_diamond_ore.png",
        },
        getModel: () => {return createBlockModel (ItemId.DiamondOreBlock)},
        blockToPlace: BlockId.DiamondOre,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.AridGrassBlock,
        name: "AridGrassBlock",
        maxStackSize: 64,
        texture: "assets/texture_arid_grass_side.png",
        textureFilenames: {
            top:    "assets/texture_arid_grass_top.png",
            front:  "assets/texture_arid_grass_side.png",
            back:   "assets/texture_arid_grass_side.png",
            left:   "assets/texture_arid_grass_side.png",
            right:  "assets/texture_arid_grass_side.png",
            bottom: "assets/texture_dirt.png",
        },
        getModel: () => {return createBlockModel (ItemId.AridGrassBlock)},
        blockToPlace: BlockId.AridGrass,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.TropicalGrassBlock,
        name: "TropicalGrassBlock",
        maxStackSize: 64,
        texture: "assets/texture_jungle_grass_side.png",
        textureFilenames: {
            top:    "assets/texture_jungle_grass_top.png",
            front:  "assets/texture_jungle_grass_side.png",
            back:   "assets/texture_jungle_grass_side.png",
            left:   "assets/texture_jungle_grass_side.png",
            right:  "assets/texture_jungle_grass_side.png",
            bottom: "assets/texture_dirt.png",
        },
        getModel: () => {return createBlockModel (ItemId.TropicalGrassBlock)},
        blockToPlace: BlockId.TropicalGrass,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.ColdGrassBlock,
        name: "ColdGrassBlock",
        maxStackSize: 64,
        texture: "assets/texture_cold_grass_side.png",
        textureFilenames: {
            top:    "assets/texture_cold_grass_top.png",
            front:  "assets/texture_cold_grass_side.png",
            back:   "assets/texture_cold_grass_side.png",
            left:   "assets/texture_cold_grass_side.png",
            right:  "assets/texture_cold_grass_side.png",
            bottom: "assets/texture_dirt.png",
        },
        getModel: () => {return createBlockModel (ItemId.ColdGrassBlock)},
        blockToPlace: BlockId.ColdGrass,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.CactusBlock,
        name: "CactusBlock",
        maxStackSize: 64,
        texture: "assets/texture_cactus_side.png",
        textureFilenames: {
            top:    "assets/texture_cactus_top.png",
            front:  "assets/texture_cactus_side.png",
            back:   "assets/texture_cactus_side.png",
            left:   "assets/texture_cactus_side.png",
            right:  "assets/texture_cactus_side.png",
            bottom: "assets/texture_cactus_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.CactusBlock)},
        blockToPlace: BlockId.Cactus,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.JungleLogBlock,
        name: "JungleLogBlock",
        maxStackSize: 64,
        texture: "assets/texture_jungle_log_top.png",
        textureFilenames: {
            top:    "assets/texture_jungle_log_top.png",
            front:  "assets/texture_jungle_log_side.png",
            back:   "assets/texture_jungle_log_side.png",
            left:   "assets/texture_jungle_log_side.png",
            right:  "assets/texture_jungle_log_side.png",
            bottom: "assets/texture_jungle_log_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.JungleLogBlock)},
        blockToPlace: BlockId.JungleLog,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.PineLogBlock,
        name: "PineLogBlock",
        maxStackSize: 64,
        texture: "assets/texture_pine_log_top.png",
        textureFilenames: {
            top:    "assets/texture_pine_log_top.png",
            front:  "assets/texture_pine_log_side.png",
            back:   "assets/texture_pine_log_side.png",
            left:   "assets/texture_pine_log_side.png",
            right:  "assets/texture_pine_log_side.png",
            bottom: "assets/texture_pine_log_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.PineLogBlock)},
        blockToPlace: BlockId.PineLog,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.AcaciaLogBlock,
        name: "AcaciaLogBlock",
        maxStackSize: 64,
        texture: "assets/texture_acacia_log_top.png",
        textureFilenames: {
            top:    "assets/texture_acacia_log_top.png",
            front:  "assets/texture_acacia_log_side.png",
            back:   "assets/texture_acacia_log_side.png",
            left:   "assets/texture_acacia_log_side.png",
            right:  "assets/texture_acacia_log_side.png",
            bottom: "assets/texture_acacia_log_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.AcaciaLogBlock)},
        blockToPlace: BlockId.AcaciaLog,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.JungleLeavesBlock,
        name: "JungleLeavesBlock",
        maxStackSize: 64,
        texture: "assets/texture_jungle_leaves.png",
        textureFilenames: {
            top:    "assets/texture_jungle_leaves.png",
            front:  "assets/texture_jungle_leaves.png",
            back:   "assets/texture_jungle_leaves.png",
            left:   "assets/texture_jungle_leaves.png",
            right:  "assets/texture_jungle_leaves.png",
            bottom: "assets/texture_jungle_leaves.png",
        },
        getModel: () => {return createBlockModel (ItemId.JungleLeavesBlock)},
        blockToPlace: BlockId.JungleLeaves,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.PineLeavesBlock,
        name: "PineLeavesBlock",
        maxStackSize: 64,
        texture: "assets/texture_pine_leaves.png",
        textureFilenames: {
            top:    "assets/texture_pine_leaves.png",
            front:  "assets/texture_pine_leaves.png",
            back:   "assets/texture_pine_leaves.png",
            left:   "assets/texture_pine_leaves.png",
            right:  "assets/texture_pine_leaves.png",
            bottom: "assets/texture_pine_leaves.png",
        },
        getModel: () => {return createBlockModel (ItemId.PineLeavesBlock)},
        blockToPlace: BlockId.PineLeaves,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.AcaciaLeavesBlock,
        name: "AcaciaLeavesBlock",
        maxStackSize: 64,
        texture: "assets/texture_acacia_leaves.png",
        textureFilenames: {
            top:    "assets/texture_acacia_leaves.png",
            front:  "assets/texture_acacia_leaves.png",
            back:   "assets/texture_acacia_leaves.png",
            left:   "assets/texture_acacia_leaves.png",
            right:  "assets/texture_acacia_leaves.png",
            bottom: "assets/texture_acacia_leaves.png",
        },
        getModel: () => {return createBlockModel (ItemId.AcaciaLeavesBlock)},
        blockToPlace: BlockId.AcaciaLeaves,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.OakWoodenPlanksBlock,
        name: "OakWoodenPlanksBlock",
        maxStackSize: 64,
        texture: "assets/texture_wooden_planks.png",
        textureFilenames: {
            top:    "assets/texture_wooden_planks.png",
            front:  "assets/texture_wooden_planks.png",
            back:   "assets/texture_wooden_planks.png",
            left:   "assets/texture_wooden_planks.png",
            right:  "assets/texture_wooden_planks.png",
            bottom: "assets/texture_wooden_planks.png",
        },
        getModel: () => {return createBlockModel (ItemId.OakWoodenPlanksBlock)},
        blockToPlace: BlockId.OakWoodenPlanks,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.JungleWoodenPlanksBlock,
        name: "JungleWoodenPlanksBlock",
        maxStackSize: 64,
        texture: "assets/texture_jungle_wooden_planks.png",
        textureFilenames: {
            top:    "assets/texture_jungle_wooden_planks.png",
            front:  "assets/texture_jungle_wooden_planks.png",
            back:   "assets/texture_jungle_wooden_planks.png",
            left:   "assets/texture_jungle_wooden_planks.png",
            right:  "assets/texture_jungle_wooden_planks.png",
            bottom: "assets/texture_jungle_wooden_planks.png",
        },
        getModel: () => {return createBlockModel (ItemId.JungleWoodenPlanksBlock)},
        blockToPlace: BlockId.JungleWoodenPlanks,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.PineWoodenPlanksBlock,
        name: "PineWoodenPlanksBlock",
        maxStackSize: 64,
        texture: "assets/texture_pine_wooden_planks.png",
        textureFilenames: {
            top:    "assets/texture_pine_wooden_planks.png",
            front:  "assets/texture_pine_wooden_planks.png",
            back:   "assets/texture_pine_wooden_planks.png",
            left:   "assets/texture_pine_wooden_planks.png",
            right:  "assets/texture_pine_wooden_planks.png",
            bottom: "assets/texture_pine_wooden_planks.png",
        },
        getModel: () => {return createBlockModel (ItemId.PineWoodenPlanksBlock)},
        blockToPlace: BlockId.PineWoodenPlanks,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.AcaciaWoodenPlanksBlock,
        name: "AcaciaWoodenPlanksBlock",
        maxStackSize: 64,
        texture: "assets/texture_acacia_wooden_planks.png",
        textureFilenames: {
            top:    "assets/texture_acacia_wooden_planks.png",
            front:  "assets/texture_acacia_wooden_planks.png",
            back:   "assets/texture_acacia_wooden_planks.png",
            left:   "assets/texture_acacia_wooden_planks.png",
            right:  "assets/texture_acacia_wooden_planks.png",
            bottom: "assets/texture_acacia_wooden_planks.png",
        },
        getModel: () => {return createBlockModel (ItemId.AcaciaWoodenPlanksBlock)},
        blockToPlace: BlockId.AcaciaWoodenPlanks,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.Stick,
        name: "Stick",
        maxStackSize: 64,
        texture: "assets/texture_stick.png",
        getModel: () => {return loadModel ("assets/models/model_stick.gltf")},
        blockToPlace: null,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.WoodenAxe,
        name: "WoodenAxe",
        maxStackSize: 1,
        texture: "assets/texture_wooden_axe.png",
        getModel: () => {return loadModel ("assets/models/model_wooden_axe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Axe,
        toolEfficiencyFactor: 2,
        toolDurabilityMax: 64,
    },
    {
        id: ItemId.WoodenHoe,
        name: "WoodenHoe",
        maxStackSize: 1,
        texture: "assets/texture_wooden_hoe.png",
        getModel: () => {return loadModel ("assets/models/model_wooden_hoe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Hoe,
        toolEfficiencyFactor: 10,
        toolDurabilityMax: 64,
    },
    {
        id: ItemId.WoodenPickaxe,
        name: "WoodenPickaxe",
        maxStackSize: 1,
        texture: "assets/texture_wooden_pickaxe.png",
        getModel: () => {return loadModel ("assets/models/model_wooden_pickaxe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Pickaxe,
        toolEfficiencyFactor: 1 / 0.16,
        toolDurabilityMax: 64,
    },
    {
        id: ItemId.WoodenShovel,
        name: "WoodenShovel",
        maxStackSize: 1,
        texture: "assets/texture_wooden_shovel.png",
        getModel: () => {return loadModel ("assets/models/model_wooden_shovel.gltf")},
        blockToPlace: null,
        toolType: ToolType.Shovel,
        toolEfficiencyFactor: 2,
        toolDurabilityMax: 64,
    },
    {
        id: ItemId.WoodenSword,
        name: "WoodenSword",
        maxStackSize: 1,
        texture: "assets/texture_wooden_sword.png",
        getModel: () => {return loadModel ("assets/models/model_wooden_sword.gltf")},
        blockToPlace: null,
        toolType: ToolType.Sword,
        toolEfficiencyFactor: 2,
        toolDurabilityMax: 64,
    },
    {
        id: ItemId.StoneAxe,
        name: "StoneAxe",
        maxStackSize: 1,
        texture: "assets/texture_stone_axe.png",
        getModel: () => {return loadModel ("assets/models/model_stone_axe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Axe,
        toolEfficiencyFactor: 3,
        toolDurabilityMax: 128,
    },
    {
        id: ItemId.StoneHoe,
        name: "StoneHoe",
        maxStackSize: 1,
        texture: "assets/texture_stone_hoe.png",
        getModel: () => {return loadModel ("assets/models/model_stone_hoe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Hoe,
        toolEfficiencyFactor: 10,
        toolDurabilityMax: 128,
    },
    {
        id: ItemId.StonePickaxe,
        name: "StonePickaxe",
        maxStackSize: 1,
        texture: "assets/texture_stone_pickaxe.png",
        getModel: () => {return loadModel ("assets/models/model_stone_pickaxe.gltf")},
        blockToPlace: null,
        toolType: ToolType.Pickaxe,
        toolEfficiencyFactor: 1 / 0.085,
        toolDurabilityMax: 128,
    },
    {
        id: ItemId.StoneShovel,
        name: "StoneShovel",
        maxStackSize: 1,
        texture: "assets/texture_stone_shovel.png",
        getModel: () => {return loadModel ("assets/models/model_stone_shovel.gltf")},
        blockToPlace: null,
        toolType: ToolType.Shovel,
        toolEfficiencyFactor: 3,
        toolDurabilityMax: 128,
    },
    {
        id: ItemId.StoneSword,
        name: "StoneSword",
        maxStackSize: 1,
        texture: "assets/texture_stone_sword.png",
        getModel: () => {return loadModel ("assets/models/model_stone_sword.gltf")},
        blockToPlace: null,
        toolType: ToolType.Sword,
        toolEfficiencyFactor: 3,
        toolDurabilityMax: 128,
    },
    {
        id: ItemId.CraftingTableBlock,
        name: "CraftingTableBlock",
        maxStackSize: 64,
        texture: "assets/texture_crafting_table_front.png",
        textureFilenames: {
            top:    "assets/texture_crafting_table_top.png",
            front:  "assets/texture_crafting_table_front.png",
            back:   "assets/texture_crafting_table_front.png",
            left:   "assets/texture_crafting_table_side.png",
            right:  "assets/texture_crafting_table_side.png",
            bottom: "assets/texture_wooden_planks.png",
        },
        getModel: () => {return createBlockModel (ItemId.CraftingTableBlock)},
        blockToPlace: BlockId.CraftingTable,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.CobblestoneBlock,
        name: "CobblestoneBlock",
        maxStackSize: 64,
        texture: "assets/texture_cobblestone.png",
        textureFilenames: {
            top:    "assets/texture_cobblestone.png",
            front:  "assets/texture_cobblestone.png",
            back:   "assets/texture_cobblestone.png",
            left:   "assets/texture_cobblestone.png",
            right:  "assets/texture_cobblestone.png",
            bottom: "assets/texture_cobblestone.png",
        },
        getModel: () => {return createBlockModel (ItemId.CobblestoneBlock)},
        blockToPlace: BlockId.Cobblestone,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.Coal,
        name: "Coal",
        maxStackSize: 64,
        texture: "assets/texture_coal.png",
        getModel: () => {return loadModel ("assets/models/model_coal.gltf")},
        blockToPlace: null,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.IronIngot,
        name: "IronIngot",
        maxStackSize: 64,
        texture: "assets/texture_iron_ingot.png",
        getModel: () => {return loadModel ("assets/models/model_iron_ingot.gltf")},
        blockToPlace: null,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.GoldIngot,
        name: "GoldIngot",
        maxStackSize: 64,
        texture: "assets/texture_gold_ingot.png",
        getModel: () => {return loadModel ("assets/models/model_gold_ingot.gltf")},
        blockToPlace: null,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.Diamond,
        name: "Diamond",
        maxStackSize: 64,
        texture: "assets/texture_diamond.png",
        getModel: () => {return loadModel ("assets/models/model_diamond.gltf")},
        blockToPlace: null,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    },
    {
        id: ItemId.ChestBlock,
        name: "ChestBlock",
        maxStackSize: 64,
        texture: "assets/texture_chest_front.png",
        textureFilenames: {
            top:    "assets/texture_chest_top.png",
            front:  "assets/texture_chest_front.png",
            back:   "assets/texture_chest_side.png",
            left:   "assets/texture_chest_side.png",
            right:  "assets/texture_chest_side.png",
            bottom: "assets/texture_chest_top.png",
        },
        getModel: () => {return createBlockModel (ItemId.ChestBlock)},
        blockToPlace: BlockId.Chest,
        toolType: ToolType.None,
        toolEfficiencyFactor: 0,
        toolDurabilityMax: 0,
    }
];