// Minecraft clone made with THREE.js
// Item Ids
// Note that this is separate from itemData to avoid circular imports
// By Amy Burnett
// =======================================================================
// Importing

// =======================================================================

// Enum of item IDs
export const ItemId = {
    AirBlock:                 0,
    GrassBlock:               1,
    DirtBlock:                2,
    StoneBlock:               3,
    SandBlock:                4,
    WaterBlock:               5,
    LogBlock:                 6,
    LeavesBlock:              7,
    CoalOreBlock:             8,
    IronOreBlock:             9,
    GoldOreBlock:             10,
    DiamondOreBlock:          11,
    AridGrassBlock:           12,
    TropicalGrassBlock:       13,
    ColdGrassBlock:           14,
    CactusBlock:              15,
    JungleLogBlock:           16,
    PineLogBlock:             17,
    AcaciaLogBlock:           18,
    JungleLeavesBlock:        19,
    PineLeavesBlock:          20,
    AcaciaLeavesBlock:        21,
    OakWoodenPlanksBlock:     22,
    JungleWoodenPlanksBlock:  23,
    PineWoodenPlanksBlock:    24,
    AcaciaWoodenPlanksBlock:  25,
    Stick:                    26,
    WoodenAxe:                27,
    WoodenHoe:                28,
    WoodenPickaxe:            29,
    WoodenShovel:             30,
    WoodenSword:              31,
    StoneAxe:                 32,
    StoneHoe:                 33,
    StonePickaxe:             34,
    StoneShovel:              35,
    StoneSword:               36,
    CraftingTableBlock:       37,
    CobblestoneBlock:         38,
    Coal:                     39,
    IronIngot:                40,
    GoldIngot:                41,
    Diamond:                  42,
    ChestBlock:               43,
    IronAxe:                  44,
    IronHoe:                  45,
    IronPickaxe:              46,
    IronShovel:               47,
    IronSword:                48,
    GoldAxe:                  49,
    GoldHoe:                  50,
    GoldPickaxe:              51,
    GoldShovel:               52,
    GoldSword:                53,
    DiamondAxe:               54,
    DiamondHoe:               55,
    DiamondPickaxe:           56,
    DiamondShovel:            57,
    DiamondSword:             58,
    RawBeef:                  59,
    RawChicken:               60,
};
